In [57]:
import numpy as np 
import pandas as pd 

train_data=pd.read_csv('train.csv')
test_data=pd.read_csv('test.csv')
print(train_data.shape)
print(test_data.shape)
train_data.head()

(9021, 98)
(10, 99)

,date_id,D1,D2,D3,D4,D5,D6,D7,D8,D9,...,V3,V4,V5,V6,V7,V8,V9,forward_returns,risk_free_rate,market_forward_excess_returns
0,0,0,0,0,1,1,0,0,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.002421,0.000301,-0.003038
1,1,0,0,0,1,1,0,0,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.008495,0.000303,-0.009114
2,2,0,0,0,1,0,0,0,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.009624,0.000301,-0.010243
3,3,0,0,0,1,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.004662,0.000299,0.004046
4,4,0,0,0,1,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.011686,0.000299,-0.012301

In [58]:
test_data.head()

,date_id,D1,D2,D3,D4,D5,D6,D7,D8,D9,...,V4,V5,V6,V7,V8,V9,is_scored,lagged_forward_returns,lagged_risk_free_rate,lagged_market_forward_excess_returns
0,8980,0,0,0,0,1,0,0,1,0,...,0.828042,0.999172,0.759921,-0.803127,0.170966,-0.751909,True,0.003541,0.000161,0.003068
1,8981,0,0,0,0,1,0,0,1,0,...,0.831349,1.120336,0.556217,-0.686192,0.141865,-0.660326,True,-0.005964,0.000162,-0.006437
2,8982,0,0,0,0,1,0,0,0,1,...,0.832672,1.088992,0.665344,-0.459367,0.199405,-0.510979,True,-0.007410,0.000160,-0.007882
3,8983,0,0,0,0,1,0,0,0,1,...,0.835979,1.040988,0.594577,-0.561643,0.161706,-0.575997,True,0.005420,0.000160,0.004949
4,8984,0,0,0,0,0,0,1,0,1,...,0.839947,0.944593,0.715608,-0.692649,0.124669,-0.654045,True,0.008357,0.000159,0.007887

我们先读取识别所有数据之后，看看样子，然后做一个初步的剪切，比如去掉ID
~~~all_features=pd.concat((train_data.iloc[:,1:-1],test_data.iloc[:,1:-1]))
    接下来是数据预处理，首先是归一化，x-mu/theta，变成零均值和标准方差

In [62]:
import numpy as np 
import pandas as pd 
##all_features=pd.concat((train_data.iloc[:,1:-1],test_data.iloc[:,1:-1]))
##print(all_features.head)
df=train_data.iloc[:,2:-1]
#train_features=train_data.loc[:,'D1':'V9']

df.to_csv('qwen_train.csv')

In [63]:
import numpy as np 
import pandas as pd 
qwen_train=pd.read_csv('qwen_train.csv')
qwen_train.head

<bound method NDFrame.head of       Unnamed: 0  D2  D3  D4  D5  D6  D7  D8  D9        E1  ...        V2  \
0              0   0   0   1   1   0   0   0   1       NaN  ...       NaN
1              1   0   0   1   1   0   0   0   1       NaN  ...       NaN
2              2   0   0   1   0   0   0   0   1       NaN  ...       NaN
3              3   0   0   1   0   0   0   0   0       NaN  ...       NaN
4              4   0   0   1   0   0   0   0   0       NaN  ...       NaN
...          ...  ..  ..  ..  ..  ..  ..  ..  ..       ...  ...       ...
9016        9016   0   0   1   0   0   0   0   0  1.493117  ...  0.541005
9017        9017   0   0   1   0   0   0   0   0  1.490889  ...  0.507937
9018        9018   0   0   1   0  -1   0   0   0  1.488667  ...  0.474868
9019        9019   0   0   1   0  -1   0   0   0  1.486451  ...  0.467593
9020        9020   0   0   1   0  -1   0   0   0  1.484241  ...  0.437831

            V3        V4        V5        V6        V7        V8        V9  \
0          NaN       NaN       NaN       NaN       NaN       NaN       NaN
1          NaN       NaN       NaN       NaN       NaN       NaN       NaN
2          NaN       NaN       NaN       NaN       NaN       NaN       NaN
3          NaN       NaN       NaN       NaN       NaN       NaN       NaN
4          NaN       NaN       NaN       NaN       NaN       NaN       NaN
...        ...       ...       ...       ...       ...       ...       ...
9016  0.208995  0.484788  0.717308  0.677249 -0.327455  0.083995 -0.380452
9017  0.082011  0.482804  1.001028  0.596561 -0.372979  0.094246 -0.427355
9018  0.334656  0.486772  0.894502  0.656746 -0.282024  0.090608 -0.381337
9019  0.163360  0.492725  1.117639  0.674603 -0.445261  0.106481 -0.477635
9020  0.177910  0.501323  1.231340  0.486111 -0.562036  0.089947 -0.543367

      forward_returns  risk_free_rate
0           -0.002421        0.000301
1           -0.008495        0.000303
2           -0.009624        0.000301
3            0.004662        0.000299
4           -0.011686        0.000299
...               ...             ...
9016        -0.000015        0.000151
9017        -0.005199        0.000150
9018         0.005930        0.000150
9019         0.008173        0.000150
9020         0.009524        0.000149

[9021 rows x 96 columns]>